### ISSUE TITLE
Import the testapp1 code

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/flask-example#1]
- Import the code for testing membrane-backend
- Ensure multiple instances can be spin up with different env vars
- Ensure that it's possible to enable / disable membrane

**Comment by rngadam** [comment]
should follow this doc:

https://github.com/ai-cfia/dev-rel-docs/blob/main/Minimal-Backend-Setup-Guides/PYTHON-BACKEND-SETUP.md
